/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculator.h"

bool_t
xdr_numbers (XDR *xdrs, numbers *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->first_number))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->second_number))
		 return FALSE;
	return TRUE;
}
