/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	float first_number;
	float second_number;
};
typedef struct numbers numbers;

#define CALCULATOR 0x23451111
#define CALCULATOR_FUNCTIONS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUM 1
extern  float * sum_1(numbers *, CLIENT *);
extern  float * sum_1_svc(numbers *, struct svc_req *);
#define SUBSTRACT 2
extern  float * substract_1(numbers *, CLIENT *);
extern  float * substract_1_svc(numbers *, struct svc_req *);
#define DIVIDE 3
extern  float * divide_1(numbers *, CLIENT *);
extern  float * divide_1_svc(numbers *, struct svc_req *);
#define MULTIPLY 4
extern  float * multiply_1(numbers *, CLIENT *);
extern  float * multiply_1_svc(numbers *, struct svc_req *);
extern int calculator_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM 1
extern  float * sum_1();
extern  float * sum_1_svc();
#define SUBSTRACT 2
extern  float * substract_1();
extern  float * substract_1_svc();
#define DIVIDE 3
extern  float * divide_1();
extern  float * divide_1_svc();
#define MULTIPLY 4
extern  float * multiply_1();
extern  float * multiply_1_svc();
extern int calculator_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
