/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"
#include <stdio.h>
 
float *
sum_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	float firstargument = 0.0f;
	float secondargument = 0.0f;

	firstargument = argp->first_number;
	secondargument = argp->second_number;

	result = firstargument + secondargument;

	printf("----- Add Calculation Information Log -----");
	printf("[ First Arg  :  %f ]", firstargument);
	printf("[ Second Arg :  %f ]", secondargument);
	printf("[ Result     :  %f ]", result);
	printf("-------------------------------------------");

	return &result;
}

float *
substract_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	float firstargument = 0.0f;
	float secondargument = 0.0f;

	firstargument = argp->first_number;
	secondargument = argp->second_number;

	result = firstargument - secondargument;

	printf("----- Substract Calculation Information Log -----");
	printf("[ First Arg  :  %f ]", firstargument);
	printf("[ Second Arg :  %f ]", secondargument);
	printf("[ Result     :  %f ]", result);
	printf("-------------------------------------------");

	return &result;
}

float *
divide_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	float firstargument = 0.0f;
	float secondargument = 0.0f;

	firstargument = argp->first_number;
	secondargument = argp->second_number;

	if(secondargument) {
		result = 0.0f;
		return &result;
	}
		

	result = firstargument / secondargument;

	printf("----- Divide Calculation Information Log -----");
	printf("[ First Arg  :  %f ]", firstargument);
	printf("[ Second Arg :  %f ]", secondargument);
	printf("[ Result     :  %f ]", result);
	printf("-------------------------------------------");

	return &result;
}

float *
multiply_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	float firstargument = 0.0f;
	float secondargument = 0.0f;

	firstargument = argp->first_number;
	secondargument = argp->second_number;

	result = firstargument * secondargument;

	printf("----- Multiply Calculation Information Log -----");
	printf("[ First Arg  :  %f ]", firstargument);
	printf("[ Second Arg :  %f ]", secondargument);
	printf("[ Result     :  %f ]", result);
	printf("-------------------------------------------");

	return &result;
}
